import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'
import { Layout } from '../Layout/Layout'
import { Logo } from '../src/components/Logo/Logo'
import { SearchBar } from '../src/components/SearchBar/SearchBar'

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Muha Engine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Wrap>
          <Logo />
          <SearchBar />
        </Wrap>
      </Layout>
    </Container>
  )
}

const Wrap = styled.div`
  min-height: calc(100vh - 60px - 45px);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 2em;
`

const Container = styled.div`
  min-height: 100vh;
  width: 100%;
  display: flex;
  flex-direction: column;
  box-sizing: border-box;
`

export default Home
